name: e_commerce_admin
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  #state management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  #remote data
  firebase_core: ^2.14.0
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.3
  google_sign_in: ^6.1.4
  #firebase_core_platform_interface: 4.5.1

  #local data
  shared_preferences: ^2.0.17

  #DI
  get_it: ^7.2.0

  # Functional programming thingies
  dartz: ^0.10.1
  equatable: ^2.0.5

  #images, gallery, video
  image_picker: ^0.8.4+8

  #svg, icon, font
  #flutter_svg: 1.1.5
  #google_fonts: 2.2.0
  #font_awesome_flutter: ^9.2.0
  #country_icons: ^2.0.2
  #fluttericon: ^2.0.0

  # navigation
  go_router: ^6.0.5
  path_to_regexp: ^0.4.0

  #others
  #intl_utils: ^2.8.3
  #pin_code_fields: ^7.4.0
  email_validator: ^2.0.1
  top_snackbar_flutter: ^2.1.1
  #flash: ^2.0.5+1
  #smooth_page_indicator: ^1.0.0+2
  #clippy_flutter: ^2.0.0-nullsafety.1
  flutter_screenutil: ^5.8.4
  #carousel_slider: ^4.1.1
  #flutter_native_splash: ^2.2.9
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_charts: ^22.2.7


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

#flutter_native_splash:
  #color: '#ffffff' 
  #image: assets/png/icons/splash_icon_1.png


flutter:

  uses-material-design: true

  assets:
    - assets/png/illustrations/
    - assets/png/icons/
    - assets/png/icons/onboarding/
    - assets/png/icons/navbar/
    - assets/images/
    - assets/images/home_slider/
    - assets/images/onboarding/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
